### ISSUE TITLE
중성 코드표가 잘못 되어 있는거 같습니다.

### ISSUE THREAD

**Issue by sukhoohong** [keepcosmos/ununiga#2]
안녕하세요. 
자소분리가 필요해서 유용하게 사용중입니다. 
테스트중에 '도쿄', '뉴욕' 등이 
'ㄷㅗㅋㅚ', 'ㄴㅠㅇㅚㄱ'  같이 잘못 분리되는것을 확인했습니다.

JUNGSUNGS = %w(ㅏ ㅐ ㅑ ㅒ ㅓ ㅔ ㅕ ㅖ ㅗ ㅘ ㅛ ㅙ ㅚ ㅜ ㅝ ㅞ ㅟ ㅠ ㅡ ㅢ ㅣ).freeze
코드 상의 ㅚ, ㅛ 등이 잘못들어간걸로 보입니다.
JUNGSUNGS = %w(ㅏ ㅐ ㅑ ㅒ ㅓ ㅔ ㅕ ㅖ ㅗ ㅘ ㅙ ㅚ ㅛ ㅜ ㅝ ㅞ ㅟ ㅠ ㅡ ㅢ ㅣ).freeze

이 순서가 맞는거 같은데, 한번 확인 부탁드립니다.

**Comment by keepcosmos** [comment]
그렇군요, 감사합니다. :)
혹시 테스트와 함께 PR 날려주실 수 있으세요?

**Comment by keepcosmos** [comment]
close #3
